### ISSUE TITLE
kube-proxy 启动失败，v1.11.2 有详细日志

### ISSUE THREAD

**Issue by timeout1423** [opsnull/follow-me-install-kubernetes-cluster#367]
kube-proxy  启动失败

失败日志是这样

Dec 04 02:41:49 kube129 systemd[1]: Started Kubernetes Kube-Proxy Server.
Dec 04 02:41:49 kube129 systemd[1]: Starting Kubernetes Kube-Proxy Server...
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.449832   12352 flags.go:27] FLAG: --alsologtostderr="true"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450294   12352 flags.go:27] FLAG: --bind-address="0.0.0.0"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450307   12352 flags.go:27] FLAG: --cleanup="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450316   12352 flags.go:27] FLAG: --cleanup-iptables="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450323   12352 flags.go:27] FLAG: --cleanup-ipvs="true"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450329   12352 flags.go:27] FLAG: --cluster-cidr=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450336   12352 flags.go:27] FLAG: --config="/etc/kube/kubeproxy/conf/kube-proxy.config.yaml"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450343   12352 flags.go:27] FLAG: --config-sync-period="15m0s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450351   12352 flags.go:27] FLAG: --conntrack-max="0"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450358   12352 flags.go:27] FLAG: --conntrack-max-per-core="32768"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450365   12352 flags.go:27] FLAG: --conntrack-min="131072"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450371   12352 flags.go:27] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450377   12352 flags.go:27] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450384   12352 flags.go:27] FLAG: --feature-gates=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450393   12352 flags.go:27] FLAG: --healthz-bind-address="0.0.0.0:10256"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450399   12352 flags.go:27] FLAG: --healthz-port="10256"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450405   12352 flags.go:27] FLAG: --help="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450411   12352 flags.go:27] FLAG: --hostname-override="kube129"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450418   12352 flags.go:27] FLAG: --iptables-masquerade-bit="14"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450423   12352 flags.go:27] FLAG: --iptables-min-sync-period="0s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450429   12352 flags.go:27] FLAG: --iptables-sync-period="30s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450435   12352 flags.go:27] FLAG: --ipvs-exclude-cidrs="[]"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450448   12352 flags.go:27] FLAG: --ipvs-min-sync-period="0s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450454   12352 flags.go:27] FLAG: --ipvs-scheduler=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450460   12352 flags.go:27] FLAG: --ipvs-sync-period="30s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450466   12352 flags.go:27] FLAG: --kube-api-burst="10"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450471   12352 flags.go:27] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450478   12352 flags.go:27] FLAG: --kube-api-qps="5"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450486   12352 flags.go:27] FLAG: --kubeconfig="/etc/kube/kubectl/conf/kube-proxy.kubeconfig"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450493   12352 flags.go:27] FLAG: --log-backtrace-at=":0"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450501   12352 flags.go:27] FLAG: --log-dir="/var/log/k8s/"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450508   12352 flags.go:27] FLAG: --log-flush-frequency="5s"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450514   12352 flags.go:27] FLAG: --logtostderr="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450519   12352 flags.go:27] FLAG: --masquerade-all="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450525   12352 flags.go:27] FLAG: --master=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450531   12352 flags.go:27] FLAG: --metrics-bind-address="127.0.0.1:10249"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450538   12352 flags.go:27] FLAG: --nodeport-addresses="[]"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450545   12352 flags.go:27] FLAG: --oom-score-adj="-999"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450551   12352 flags.go:27] FLAG: --profiling="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450556   12352 flags.go:27] FLAG: --proxy-mode=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450564   12352 flags.go:27] FLAG: --proxy-port-range=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450571   12352 flags.go:27] FLAG: --resource-container="/kube-proxy"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450578   12352 flags.go:27] FLAG: --stderrthreshold="2"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450585   12352 flags.go:27] FLAG: --udp-timeout="250ms"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450591   12352 flags.go:27] FLAG: --v="2"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450597   12352 flags.go:27] FLAG: --version="false"
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450605   12352 flags.go:27] FLAG: --vmodule=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450611   12352 flags.go:27] FLAG: --write-config-to=""
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.451385   12352 feature_gate.go:230] feature gates: &{map[]}
Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.492806   12352 server.go:413] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
Dec 04 02:41:49 kube129 kube-proxy[12352]: F1204 02:41:49.492854   12352 server.go:361] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
Dec 04 02:41:49 kube129 kube-proxy[12352]: goroutine 1 [running]:
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc42068a500, 0xc42050a000, 0x81, 0x9e)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xcf
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x21d19c0, 0xc400000003, 0xc4200e2370, 0x20014c8, 0x9, 0x169, 0x0)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x30f
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printDepth(0x21d19c0, 0xc400000003, 0x1, 0xc420915c40, 0x1, 0x1)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:646 +0x129
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).print(0x21d19c0, 0xc400000003, 0xc420915c40, 0x1, 0x1)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:637 +0x5a
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/golang/glog.Fatal(0xc420915c40, 0x1, 0x1)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1125 +0x53
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc42038e000, 0xc42055a310, 0x0, 0x7)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:361 +0x19b
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42038e000, 0xc4200a2010, 0x7, 0x7, 0xc42038e000, 0xc4200a2010)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42038e000, 0xc420376810, 0x16813b0, 0xc420873ee8)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
Dec 04 02:41:49 kube129 kube-proxy[12352]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42038e000, 0x16827a0, 0x21d16a0)
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
Dec 04 02:41:49 kube129 kube-proxy[12352]: main.main()
Dec 04 02:41:49 kube129 kube-proxy[12352]: /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/proxy.go:49 +0x196
Dec 04 02:41:49 kube129 systemd[1]: kube-proxy.service: main process exited, code=exited, status=255/n/a
Dec 04 02:41:49 kube129 systemd[1]: Unit kube-proxy.service entered failed state.
Dec 04 02:41:49 kube129 systemd[1]: kube-proxy.service failed.

错误地方

Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.492806   12352 server.go:413] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
Dec 04 02:41:49 kube129 kube-proxy[12352]: F1204 02:41:49.492854   12352 server.go:361] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

但是我已经提供了kubeconfig 

Dec 04 02:41:49 kube129 kube-proxy[12352]: I1204 02:41:49.450486   12352 flags.go:27] FLAG: --kubeconfig="/etc/k8s/kubectl/conf/kube-proxy.kubeconfig"

配置文件
cat kube-proxy.config.yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 192.168.2.129
mode: ipvs
metricsBindAddress: 192.168.2.129:10249
kind: KubeProxyConfiguration
healthzBindAddress: 192.168.2.129:10256
clusterCIDR: 172.16.0.0/16
hostnameOverride: kube129
clientConnection:
  Kubeconfig: /etc/kube/kubectl/conf/kube-proxy.kubeconfig

 cat  /etc/kube/kubectl/conf/kube-proxy.kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  nRIVS85CmlJUlNWOTl5eVJwRFZKMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGSFpMcW9HV2p6R3VSUzBiTlZCaE9mSDMrZE9mTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQlBMNkVQM0w3dlAzaVAwMlV0NkdldWMvcG9hc2d4bkRFNjVJUmxKdHBHV3QrZ0JtTHkrbEx5CkZJbHl5cUc4a054VVVkN2taTFhqZGNDWUZEeDQ1TTJwNFRNUDFYM2RDaVoyVngvVkRNOHpvTVVLZ3VYa2d5anMKNXNqbStjMDI3NHhNUXQ2eWlPZmtrYnBGMTBuRkYrSG13UDQ5TmFkejRDUGtFWTNBQTB4TU4rTnUvQ0wzS2d5agpvTVpIL2RNZG9MMVRtQW5MVXNreXhISVd1YWZVT2NQbVJnUWxJelRDMWJvY3JLbU1mOG1Eby9KeklKcUJNNWJhCnRKVzVSeUVlaEFLVHZiMHBGTVRvNjErU08ralZteFFVbkxzeXdRdDJvM3krWDhnNlNtOS9ELy92Ui9UYnhkTEwKNFkxRm5qVzltblU1UldlenRxWW1MVW1Ydm5yU2hJUVUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.2.129:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kube-proxy
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: kube-proxy
  user:
    client-certificate-data:  VdTJHMjEzKzVIaUcxSGtyOHRxRnRUeHRMQ0ltRVdTc1hUbm95azVjZFNVOVEyUgpHRjdwak9zbExnNk5JYTkxcDBzSFRsbFRYWk1CcDVjbmZqaHNrazhDaUJ1UGl1QzlXdW1IaDZmSThUNDFNL2ZUClNBQ0tXdno2T2lMOFRPV1kwTm9NUmc2M2F4U29VOFZnbkYrWk1nZ1VIdmYzdGU2VURZOGNoMGU4MjBNb3FnV3QKVXE4L3pJVGd4aU9vZUQxME55dFBxVTZIRjliL1E5cVFmZFpMbUNJMVNndW0zZm04bDJNWWlyQ3JFZkQ1MXlTSAo3ZlZCMys1cUQraXZwajFWbkJHZXJnWU5Gcnl6cWhTcndGUmlxM0lxSjhDcFl6a2p0UndjUXc2ZzN6ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data:  TTJIelJNWTBMagoxY2NpWUljNGFjTDFmeXRrcy9qdVgyU2V6RXFxK1ZvQkw4Vy9ETTNwRUZ6emttcTZCeEVNNmltdmlUVUhrcGdtCm9sK0Y2QmtDZ1lBNytsbjNhT1BxMkRxZXB6cGVrWWtGQnZBTXdRbTd4TkxqOWx2blRZTmh2dXg2bTVsMDZKTjIKVGpLQUF4THhjZDBmQXd5OE0yNWxEcXpvcWpSZVJVeUw2OVdLOUdheWJXZUFPMFErUWpIQk9DZWM5MmVUMDFzQwpOWmVybHR1ZkpaeFR4b0c4d1V1bk5GWTVicVNYT0pLdk5yTW1FSkE0UEZrbGU3d25HRWpDUXc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

好像1.11.2 的 proxy 不能接受  这个 kubeconfig的格式  1.10 的版本运行就可以通过。

**Comment by mingziV5** [comment]
把启动命令直接贴终端里执行，错误会更明显

**Comment by timeout1423** [comment]
这里文档是错的 因为新版本的不支持 这个格式的配置 用命令行才可以
