### ISSUE TITLE
 kubeadm token list --kubeconfig ~/.kube/config

### ISSUE THREAD

**Issue by q1054261752** [opsnull/follow-me-install-kubernetes-cluster#434]
执行 
[k8s@kube-node1 kubernetes]$ kubeadm token list --kubeconfig ~/.kube/config
failed to list bootstrap tokens: Internal error occurred: unable to transform key "/registrycrets/kube-system/attachdetach-controller-token-fm7t6": invalid padding on input
报错

在细看发现kube-controller-manager有问题，一直重启
jsounalctl -xefu kube-controller-manager

`13949 core.go:151] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: W0409 15:53:42.590356   13949 controllermanager.go:508] Skipping "route"
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: I0409 15:53:42.590392   13949 controllermanager.go:501] Starting "serviceaccount"
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: I0409 15:53:42.597341   13949 controller_utils.go:1027] Waiting for caches to sync for tokens controller
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: E0409 15:53:42.620962   13949 reflector.go:134] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.Secret: Internal error
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: F0409 15:53:42.637981   13949 client_builder.go:258] unable to get token for service account: Internal error occurred: unable to tra
4月 09 15:53:42 kube-node1 kube-controller-manager[13949]: goroutine 105 [running]:
`

: Failed to list *v1.Secret: Internal error

**Comment by q1054261752** [comment]
https://github.com/kubernetes/kubernetes/issues/66844

可能是这个问题吗？
